### ISSUE TITLE
make installs fails on empty DESTDIR tree

### ISSUE THREAD

**Issue by xmw** [Nadrin/xlsh#1]
... as seen on Gentoo ebuild install phase (program gets installed into an clean subtree and merged into / afterwards).

--- Makefile.orig       2011-10-19 22:58:41.692800717 +0200
+++ Makefile    2011-10-19 23:04:57.708099876 +0200
@@ -56,7 +56,7 @@
        $(INSTALL_DATA) etc/Xresources $(DESTDIR)$(sysconfdir)/xlsh

 installdirs:
-       $(INSTALL_DIR) $(DESTDIR)$(sbindir) $(DESTDIR)$(sysconfdir)/xlsh
- ```
    $(INSTALL_DIR) $(DESTDIR)$(sbindir) $(DESTDIR)$(sysconfdir)/xlsh $(DESTDIR)$(sysconfdir)/pam.d
  ```
  
  uninstall:
        rm -f ${DESTDIR}$(sbindir)/xlsh

**Comment by Nadrin** [comment]
Thanks for reporting. It's now fixed.

**Comment by xmw** [comment]
http://git.overlays.gentoo.org/gitweb/?p=dev/xmw.git;a=tree;f=sys-apps/xlsh;hb=HEAD

**Comment by Nadrin** [comment]
Does it mean xlsh is going to become official Gentoo ebuild? :) Excuse me if this is a stupid question, I never used Gentoo and therefore I'm clueless about its development process.

**Comment by xmw** [comment]
I'm an Gentoo developer and can add it to the tree, once it's fit, well tested and user request. 
The mentioned git overlay is just my testing stuff on gentoo infra.

I just co-authored [1] in an attempt to strike down xdm/gdm on one single sheet of paper.

Michael

[1] http://git.overlays.gentoo.org/gitweb/?p=dev/xmw.git;a=blob;f=x11-misc/trivdm/files/trivdm-0_p20111010;h=30de0bed714e3f3b15f489fe62256b2f47f37ef5;hb=HEAD
